version: '2'
services:
#  apache:
#    build:
#      context: customDockerfiles/apache
#      dockerfile: Dockerfile
#    container_name: vs-apache
#    #environment:
#      #- ALLOW_OVERRIDE=false
#    depends_on:
#      - php
#    ports:
#      - 6180:80
#    networks:
#      - appnet
#    volumes:
#      - ./public:/var/www/html
	nginx:
	    image: tutum/nginx
	    ports:
		- "80:80"
	    links:
		- phpfpm
	    volumes:
		- ./nginx/default:/etc/nginx/sites-available/default
		- ./nginx/default:/etc/nginx/sites-enabled/default

		- ./logs/nginx-error.log:/var/log/nginx/error.log
		- ./logs/nginx-access.log:/var/log/nginx/access.log
	phpfpm:
	    image: php:fpm
	    ports:
		- "9000:9000"
	    volumes:
		- ./public:/usr/share/nginx/html
		- ./php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
	mysql:
	  image: mariadb
	  environment:
	    MYSQL_ROOT_PASSWORD: admin
	  ports:
	    - "3306:3306" 
	phpmyadmin:
	  image: phpmyadmin/phpmyadmin
	  restart: always
	  links:
	    - mysql
	  ports:
	    - 8183:80
	  environment:
	    PMA_USER: root
	    PMA_PASSWORD: admin
	    PMA_ARBITRARY: 1
networks:
  appnet:
    driver: bridge
    ipam:
        driver: default
        config:
          - subnet: 172.58.238.0/24
            gateway: 172.58.238.1
