version: '2'
services:
  web:
    container_name: web
    restart: always
    build: ./web
    expose:
      - "8000"
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - ./web:/usr/src/app
      - ./web/static:/usr/src/app/static
      #- /usr/src/app
      #- /usr/src/app/static
    env_file: .env
    environment:
      DEBUG: 'true'
    command: /usr/local/bin/gunicorn docker_django.wsgi:application -w 2 -b :8000
    networks:
      - appnet

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - /www/static
      #- ./nginx/nginx:/etc/nginx
      - ./nginx/logs/:/var/log/nginx
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
    volumes_from:
      - web
    links:
      - web:web
    depends_on:
      - web
    networks:
      - appnet

  postgres:
    container_name: db
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    networks:
      - appnet

  redis:
    container_name: redis
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data
    networks:
      - appnet

#  pgadmin:
#    container_name: pgadmin
#    links:
#      - postgres:postgres
#    image: fenglc/pgadmin4
#    volumes:
#       - /data/pgadmin:/root/.pgadmin
#    environment:
#      DEFAULT_USER: root
#      DEFAULT_PASSWORD: hide
#    ports:
#      - "5050:5050"
#    networks:
#      - appnet
#    restart: unless-stopped
networks:
  appnet:
    driver: bridge
    ipam:
        driver: default
        config:
          - subnet: 172.58.244.0/24
            gateway: 172.58.244.1